### ISSUE TITLE
window_entropy.py -- For python2 , the log2() function errors

### ISSUE THREAD

**Issue by dukeofdisaster** [keithjjones/malgazer#1]
For anyone using this with python2, window_entropy.py will fail because it calls entropy.py, which makes use of log2(), which isn't supported in python2, instead, if you change the instances to the correct format for python2, log(x, 2) the script will run fine

macOS High Sierra 10.13.12, python 2.7.14

**Comment by keithjjones** [comment]
Thanks.  I don't use Python2 for development on this, so that is good to know.

**Comment by keithjjones** [comment]
I just added a commit to change log2 to log, to make it easier for you.

**Comment by dukeofdisaster** [comment]
Thanks, I didn't think before I raised that issue a long time ago, I could
have used it for my own purposes without doing that, sorry for any
inconvenience lol :)

**Comment by keithjjones** [comment]
No problem.
